/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package org.bug.detection.ui;

import java.util.logging.Logger;
import javax.swing.JOptionPane;
import org.netbeans.api.project.Project;
import org.netbeans.api.project.ui.OpenProjects;

/**
 *
 * @author karayel
 */
public class BugDetectionFrame extends java.awt.Frame {
    
    private final static Logger log = Logger.getLogger(BugDetectionFrame.class.getName());

    private Project[] p;
    private String[] s;

    /**
     * Creates new form BugDetectionFrame
     */
    public BugDetectionFrame() {
        initComponents();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        projectsComboBox = new javax.swing.JComboBox<>();
        helpButton = new javax.swing.JButton();
        inspectButton = new javax.swing.JButton();
        cancelButton = new javax.swing.JButton();
        scopeLabel = new javax.swing.JLabel();
        jComboBox1 = new javax.swing.JComboBox<>();
        Type = new javax.swing.JLabel();

        setResizable(false);

        p = OpenProjects.getDefault().getOpenProjects();
        s = new String[p.length];
        for(int i=0;i<s.length;i++){
            s[i] = p[i].getProjectDirectory().getNameExt();
        }
        projectsComboBox.setModel(new javax.swing.DefaultComboBoxModel<>(s));

        org.openide.awt.Mnemonics.setLocalizedText(helpButton, "Help");
        helpButton.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                helpButtonActionPerformed(evt);
            }
        });

        org.openide.awt.Mnemonics.setLocalizedText(inspectButton, "Inspect");
        inspectButton.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                inspectButtonActionPerformed(evt);
            }
        });

        org.openide.awt.Mnemonics.setLocalizedText(cancelButton, "Cancel");
        cancelButton.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                cancelButtonActionPerformed(evt);
            }
        });

        org.openide.awt.Mnemonics.setLocalizedText(scopeLabel, org.openide.util.NbBundle.getMessage(BugDetectionFrame.class, "BugDetectionFrame.scopeLabel.text")); // NOI18N

        jComboBox1.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "Project Folder", "Bug Type" }));

        org.openide.awt.Mnemonics.setLocalizedText(Type, org.openide.util.NbBundle.getMessage(BugDetectionFrame.class, "BugDetectionFrame.Type.text")); // NOI18N

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(this);
        this.setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGap(0, 0, Short.MAX_VALUE)
                .addComponent(inspectButton)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(cancelButton)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(helpButton)
                .addContainerGap())
            .addGroup(layout.createSequentialGroup()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(Type, javax.swing.GroupLayout.PREFERRED_SIZE, 91, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                        .addContainerGap()
                        .addComponent(scopeLabel)
                        .addGap(8, 8, 8)))
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jComboBox1, 0, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(projectsComboBox, 0, 314, Short.MAX_VALUE)))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(projectsComboBox, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(scopeLabel))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jComboBox1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(Type))
                .addGap(14, 14, 14)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(inspectButton)
                    .addComponent(cancelButton)
                    .addComponent(helpButton))
                .addContainerGap())
        );

        pack();
        setLocationRelativeTo(null);
    }// </editor-fold>//GEN-END:initComponents
    /**
     * Inspect Button Action
     * @param evt 
     */
    private void inspectButtonActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_inspectButtonActionPerformed
        // TODO add your handling code here:
        
        if(p.length == 0){
            String title = "Inspection Error";
            String message = "Open project not found. Please, open a project";
            
            log.warning(message);
            JOptionPane.showMessageDialog(this, message, title, JOptionPane.ERROR_MESSAGE);
            
            return;
        }
        log.warning("The project has been selected.");
        Project project = p[projectsComboBox.getSelectedIndex()];
        int selectedId = jComboBox1.getSelectedIndex();
        
        log.warning("BugDetectionTopComponent is ready to open.");
        BugDetectionTopComponent bugDetectionTopComponent = new BugDetectionTopComponent(project,selectedId);
        bugDetectionTopComponent.open();
        
        setVisible(false);
    }//GEN-LAST:event_inspectButtonActionPerformed
    /**
     * Cancel Button Action
     * @param evt 
     */
    private void cancelButtonActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_cancelButtonActionPerformed
        dispose();
    }//GEN-LAST:event_cancelButtonActionPerformed
    /**
     * Help button action
     * @param evt 
     */
    private void helpButtonActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_helpButtonActionPerformed
        // TODO add your handling code here:
        JOptionPane.showMessageDialog(this,
                "Please send an e-mail to mert.karayel@isik.edu.tr for any kind of need",
                "Help",
                JOptionPane.WARNING_MESSAGE);
    }//GEN-LAST:event_helpButtonActionPerformed

     

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JLabel Type;
    private javax.swing.JButton cancelButton;
    private javax.swing.JButton helpButton;
    private javax.swing.JButton inspectButton;
    private javax.swing.JComboBox<String> jComboBox1;
    private javax.swing.JComboBox<String> projectsComboBox;
    private javax.swing.JLabel scopeLabel;
    // End of variables declaration//GEN-END:variables

}
